// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Ixh-8QCn0Zd80kqEWWErKrqnneRNn-M',
    appId: '1:551776672781:web:77c46c54535d4eee140944',
    messagingSenderId: '551776672781',
    projectId: 'comicvproject',
    authDomain: 'comicvproject.firebaseapp.com',
    storageBucket: 'comicvproject.firebasestorage.app',
    measurementId: 'G-WY196ZN3C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ryh-pI8YmtlF6AVKmdFtdzTnCV90r_8',
    appId: '1:551776672781:android:ac115d0881a79b68140944',
    messagingSenderId: '551776672781',
    projectId: 'comicvproject',
    storageBucket: 'comicvproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlB_OHhEbw3GDnjCWZMbPitgW8ymWYMFg',
    appId: '1:551776672781:ios:988eff9b7d6652b9140944',
    messagingSenderId: '551776672781',
    projectId: 'comicvproject',
    storageBucket: 'comicvproject.firebasestorage.app',
    iosBundleId: 'com.example.comicvProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlB_OHhEbw3GDnjCWZMbPitgW8ymWYMFg',
    appId: '1:551776672781:ios:988eff9b7d6652b9140944',
    messagingSenderId: '551776672781',
    projectId: 'comicvproject',
    storageBucket: 'comicvproject.firebasestorage.app',
    iosBundleId: 'com.example.comicvProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Ixh-8QCn0Zd80kqEWWErKrqnneRNn-M',
    appId: '1:551776672781:web:c753baf039d2b057140944',
    messagingSenderId: '551776672781',
    projectId: 'comicvproject',
    authDomain: 'comicvproject.firebaseapp.com',
    storageBucket: 'comicvproject.firebasestorage.app',
    measurementId: 'G-T1D9BBNHY5',
  );
}
